### ISSUE TITLE
data set summary 

### ISSUE THREAD

**Issue by ake123** [NCBI-Codeathons/amr-2024-team-lahti#10]
data set summary - Prepare a short summary of a few slides on the study and data set to be presented on a slide set @mahkamehsalehi

**Comment by antagomir** [comment]
Make the Quarto draft available in github, even if it is not ready. You can then commit improvements.

**Comment by 0xMuluh** [comment]
can we close this @mahkamehsalehi ?

**Comment by mahkamehsalehi** [comment]
Yes, sure!
