### ISSUE TITLE
Create one or more tutorials

### ISSUE THREAD

**Issue by ake123** [NCBI-Codeathons/amr-2024-team-lahti#11]
Create one or more tutorials on resistome data analysis using the latest R/Bioconductor methods and release them via the Github repository (vignettes/ subfolder).

Note: the current vignettes are Rmd but we should do them with Quarto (qmd).

**Comment by antagomir** [comment]
Start by creating a short [vignette](https://github.com/NCBI-Codeathons/amr-2024-team-lahti/tree/main/vignettes) that reads in data and generates some summary and visualization.

You can use for instance example code from [Google doc](https://docs.google.com/document/d/1ZNRfoqNzRSga6qs5L3WHKGRBpaXaclyRAmPTZnQksMo/edit) but feel free to expand or improve.

If you get the qmd slides done on data introduction, you could link them here.

**Comment by antagomir** [comment]
Initiate exploratory analysis workflow, and ensure that it will appear on the project homepage articles. We can then discuss how to develop it further. Could be reading the data, providing PCoA visualization and some other useful statistics.

You can also check if you could add initial summary on linking with NDARO?

**Comment by 0xMuluh** [comment]
Should we consider opening another issue for replicating visualization from the study?

**Comment by antagomir** [comment]
Yes, thanks
