### ISSUE TITLE
Prepare flow diagram 

### ISSUE THREAD

**Issue by ake123** [NCBI-Codeathons/amr-2024-team-lahti#9]
Prepare flow diagram

**Comment by ake123** [comment]
@microDM

**Comment by antagomir** [comment]
Was this already done for yesterday's slide presentation?

**Comment by nixonbyl** [comment]
The flow diagram was already done in yesterday's presentation.

**Comment by antagomir** [comment]
SOunds good. Could you add the flow diagram in the README.

Also add the presentation slides in Github, and link to them in README.

**Comment by microDM** [comment]
Added workflow into README and standout presentation/transcript. I think we can close this issue now.
